[package]
name = "hants"
version = "0.1.0"
edition = "2024"
description = "HANdy ToolSet - A lightweight CLI utility that consolidates several small tools to streamline everyday development tasks."
authors = ["Ivan Nosar"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ivan-nosar/hants"
homepage = "https://github.com/ivan-nosar/hants"
keywords = ["cli", "toolset", "password", "base64", "utility"]
categories = ["command-line-utilities"]

[package.metadata.wix]
upgrade-guid = "B42700BC-62F5-4376-9B9C-14C753DAC518"
path-guid = "BBBDEE8E-7F81-4F1E-9BE8-6A79C7F8E4B4"
license = false
eula = false

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
arboard = "3.6.1"
rand = "0.10.1"

[dev-dependencies]
tempfile = "3.27.0"

[profile.release]
# Instructions: https://github.com/johnthagen/min-sized-rust
opt-level = 3       # Optimize for execution speed over binary size
lto = "fat"         # Enable Link-Time Optimization to strip dead code
codegen-units = 1   # Maximize size reduction optimizations
panic = "abort"     # Remove stack unwinding logic
strip = true        # Strip debugging symbols

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
